### ISSUE TITLE
wled enablement

### ISSUE THREAD

**Issue by 99degree** [sm7150-mainline/linux#23]
hi there,

I didnt follow the wled enablement issue quite closely, but your welcome to test for my change to wled driver to get over some issue for irq storm issue.

briefly description is, my understanding, the ovp irq handler did not disable the irq at very first entry thus caused a lot of problem.
side issue is the irq handler did not aquire irq as falling edge (according to dts).

also there is a issue that enable led modulation reg caused the irq storm (as a consequence above), and the code use an "interesting" mechanism to "enable" reg later :-( ......at a tasklet...it is not wrong but.... And my change is to move that write enable reg to a sched_delay_tasklet and guarded by disable/enable_irq and retain the old code flow. and that change also "fixed" the unbalanced enable_irq issue.

My side it is showing great and irq happened only once and no more irq storm afterward. in pmos plasma i can change brightness too. plz have a test if you are interested to have a try.

P.S. somehow the commit is spreading to many changesets by iterations.... and the important one is that third one. 
[51d6386f72a078950c1ca64c536c56a838888b08
](https://github.com/99degree/linux/commit/51d6386f72a078950c1ca64c536c56a838888b08)
https://github.com/99degree/linux/commit/ae545c70321f47e97a636f1114caabff5770b5e1
https://github.com/99degree/linux/commit/a86b4c8e1563565e4f3e5910266616a607b1eb67

regards,
99degree

**Comment by JIaxyga** [comment]
Where can I contact you? Can you write to me at my email [danila@jiaxyga.com](mailto:danila@jiaxyga.com) or telegram @JIaxyga or matrix @JIaxyga:matrix.org?
