### ISSUE TITLE
nt36xxx.c Errors

### ISSUE THREAD

**Issue by blackmeat1225** [sm7150-mainline/linux#24]
CC      drivers/input/touchscreen/nt36672c/nt36xxx.o
../drivers/input/touchscreen/nt36672c/nt36xxx.c: In function ‘nvt_ts_probe’:
../drivers/input/touchscreen/nt36672c/nt36xxx.c:1833:15: error: implicit declaration of function ‘msm_drm_register_client’; did you mean ‘fb_unregister_client’? [-Werror=implicit-function-declaration]
 1833 |         ret = msm_drm_register_client(&ts->drm_notif);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
      |               fb_unregister_client
../drivers/input/touchscreen/nt36672c/nt36xxx.c:1906:13: error: implicit declaration of function ‘msm_drm_unregister_client’; did you mean ‘fb_unregister_client’? [-Werror=implicit-function-declaration]
 1906 |         if (msm_drm_unregister_client(&ts->drm_notif))
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             fb_unregister_client
../drivers/input/touchscreen/nt36672c/nt36xxx.c: In function ‘nvt_drm_notifier_callback’:
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2324:31: error: invalid use of undefined type ‘struct msm_drm_notifier’
 2324 |         if (!evdata || (evdata->id != 0))
      |                               ^~
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2327:19: error: invalid use of undefined type ‘struct msm_drm_notifier’
 2327 |         if (evdata->data && ts) {
      |                   ^~
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2328:31: error: invalid use of undefined type ‘struct msm_drm_notifier’
 2328 |                 blank = evdata->data;
      |                               ^~
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2329:30: error: ‘DRM_EARLY_EVENT_BLANK’ undeclared (first use in this function)
 2329 |                 if (event == DRM_EARLY_EVENT_BLANK) {
      |                              ^~~~~~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2329:30: note: each undeclared identifier is reported only once for each function it appears in
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2330:38: error: ‘DRM_BLANK_POWERDOWN’ undeclared (first use in this function); did you mean ‘FB_BLANK_POWERDOWN’?
 2330 |                         if (blank == DRM_BLANK_POWERDOWN) {
      |                                      ^~~~~~~~~~~~~~~~~~~
      |                                      FB_BLANK_POWERDOWN
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2335:37: error: ‘DRM_EVENT_BLANK’ undeclared (first use in this function); did you mean ‘FB_EVENT_BLANK’?
 2335 |                 } else if (event == DRM_EVENT_BLANK) {
      |                                     ^~~~~~~~~~~~~~~
      |                                     FB_EVENT_BLANK
../drivers/input/touchscreen/nt36672c/nt36xxx.c:2336:38: error: ‘DRM_BLANK_UNBLANK’ undeclared (first use in this function); did you mean ‘FB_BLANK_UNBLANK’?
 2336 |                         if (blank == DRM_BLANK_UNBLANK) {
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      FB_BLANK_UNBLANK
cc1: some warnings being treated as errors
make[7]: *** [../scripts/Makefile.build:243: drivers/input/touchscreen/nt36672c/nt36xxx.o] Error 1
make[6]: *** [../scripts/Makefile.build:480: drivers/input/touchscreen/nt36672c] Error 2
make[5]: *** [../scripts/Makefile.build:480: drivers/input/touchscreen] Error 2
make[4]: *** [../scripts/Makefile.build:480: drivers/input] Error 2
make[3]: *** [../scripts/Makefile.build:480: drivers] Error 2
make[2]: *** [/kernel/linux-6.6.1-r0/Makefile:1913: .] Error 2
make[1]: *** [/kernel/linux-6.6.1-r0/Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/kernel/linux-6.6.1-r0/out'
make: *** [Makefile:234: __sub-make] Error 2

Change the include  now new problem

  UPD     include/generated/utsversion.h
  CC      init/version-timestamp.o
  LD      .tmp_vmlinux.kallsyms1
aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
aarch64-linux-gnu-ld: drivers/input/touchscreen/nt36672c/nt36xxx.o: in function `nvt_ts_shutdown':
/kernel/linux-6.6.1-r0/out/../drivers/input/touchscreen/nt36672c/nt36xxx.c:2087: undefined reference to `msm_drm_unregister_client'
aarch64-linux-gnu-ld: drivers/input/touchscreen/nt36672c/nt36xxx.o: in function `nvt_ts_remove':
/kernel/linux-6.6.1-r0/out/../drivers/input/touchscreen/nt36672c/nt36xxx.c:2004: undefined reference to `msm_drm_unregister_client'
aarch64-linux-gnu-ld: drivers/input/touchscreen/nt36672c/nt36xxx.o: in function `nvt_ts_probe':
/kernel/linux-6.6.1-r0/out/../drivers/input/touchscreen/nt36672c/nt36xxx.c:1837: undefined reference to `msm_drm_register_client'
aarch64-linux-gnu-ld: /kernel/linux-6.6.1-r0/out/../drivers/input/touchscreen/nt36672c/nt36xxx.c:1910: undefined reference to `msm_drm_unregister_client'
make[3]: *** [../scripts/Makefile.vmlinux:36: vmlinux] Error 1
make[2]: *** [/kernel/linux-6.6.1-r0/Makefile:1165: vmlinux] Error 2
make[1]: *** [/kernel/linux-6.6.1-r0/Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/kernel/linux-6.6.1-r0/out'
make: *** [Makefile:234: __sub-make] Error 2

**Comment by blackmeat1225** [comment]
wrong .config

**Comment by JIaxyga** [comment]
I dont see such issues with v6.7.4, closed
