### ISSUE TITLE
android adbd daemon on postmarketos edge

### ISSUE THREAD

**Issue by 99degree** [sm7150-mainline/linux#25]
hey guys,
i finally make with success the known and
 old adbd-linux project run under pmos. i believe it should be useful for phone os debugging on many cases. So no more soldering iron for uart

the tool largely lack of feature by compare to android one. to make it clean and lean, i also morph the code and let it compiled as static binary and free with bionic, glibc and musl, kind of android Ubuntu alpine, futher more to break off depend on openssl so dont expect it as secure much. basically adb shell adb push is fine and small enough to live in initramdisk after strip. 

the only known issue is lack of apkbuild for pmos build automation inclusion.

you can have a trial easily by pmbootstrap
a new img, or replace init and init_functions.sh manually and put the compiled adbd file into initramfs/sbin/ and chmod a+x before repack img. The compile procedure ref to adbd-linux git log. or use adb.sh with adbd binary to test solely.

adbd-linux
https://github.com/99degree/adbd-linux.git

init is lived in pmaports:
https://github.com/99degree/pmaports.git

**Comment by ungeskriptet** [comment]
You should upstream this to postmarketOS and not here
